-- MySQL Script generated by MySQL Workbench
-- Mon Feb 26 16:45:26 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema WebShop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `WebShop` ;

-- -----------------------------------------------------
-- Schema WebShop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WebShop` DEFAULT CHARACTER SET utf8 ;
USE `WebShop` ;

-- -----------------------------------------------------
-- Table `WebShop`.`ProductTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WebShop`.`ProductTypes` ;

CREATE TABLE IF NOT EXISTS `WebShop`.`ProductTypes` (
  `TypeID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`TypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebShop`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WebShop`.`Products` ;

CREATE TABLE IF NOT EXISTS `WebShop`.`Products` (
  `ProductID` INT NOT NULL,
  `ProductTypeID` INT NOT NULL,
  `Title` TINYTEXT NOT NULL,
  `Description` TEXT NOT NULL,
  `Price` INT NOT NULL,
  PRIMARY KEY (`ProductID`),
  INDEX `fk_Products_Types1_idx` (`ProductTypeID` ASC),
  CONSTRAINT `fk_Products_Types1`
    FOREIGN KEY (`ProductTypeID`)
    REFERENCES `WebShop`.`ProductTypes` (`TypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebShop`.`Images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WebShop`.`Images` ;

CREATE TABLE IF NOT EXISTS `WebShop`.`Images` (
  `ImageID` INT NOT NULL AUTO_INCREMENT,
  `Url` TINYTEXT NULL,
  `ProductID` INT NOT NULL,
  PRIMARY KEY (`ImageID`),
  INDEX `fk_Images_Products_idx` (`ProductID` ASC),
  CONSTRAINT `fk_Images_Products`
    FOREIGN KEY (`ProductID`)
    REFERENCES `WebShop`.`Products` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebShop`.`Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WebShop`.`Comments` ;

CREATE TABLE IF NOT EXISTS `WebShop`.`Comments` (
  `CommentID` INT NOT NULL AUTO_INCREMENT,
  `Nickname` VARCHAR(45) NOT NULL,
  `Rating` INT NULL,
  `Message` TEXT NULL,
  `Date` DATE NOT NULL,
  `ProductID` INT NOT NULL,
  PRIMARY KEY (`CommentID`),
  INDEX `fk_Comments_Products1_idx` (`ProductID` ASC),
  CONSTRAINT `fk_Comments_Products1`
    FOREIGN KEY (`ProductID`)
    REFERENCES `WebShop`.`Products` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebShop`.`CharacteristicTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WebShop`.`CharacteristicTypes` ;

CREATE TABLE IF NOT EXISTS `WebShop`.`CharacteristicTypes` (
  `CharacteristicTypeID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`CharacteristicTypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebShop`.`Characteristics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WebShop`.`Characteristics` ;

CREATE TABLE IF NOT EXISTS `WebShop`.`Characteristics` (
  `CharacteristicID` INT NOT NULL AUTO_INCREMENT,
  `CharacteristicTypeID` INT NOT NULL,
  `Value` TEXT NULL,
  `ProductID` INT NOT NULL,
  PRIMARY KEY (`CharacteristicID`),
  INDEX `fk_Characteristics_CharacteristicTypes1_idx` (`CharacteristicTypeID` ASC),
  INDEX `fk_Characteristics_Products1_idx` (`ProductID` ASC),
  CONSTRAINT `fk_Characteristics_CharacteristicTypes1`
    FOREIGN KEY (`CharacteristicTypeID`)
    REFERENCES `WebShop`.`CharacteristicTypes` (`CharacteristicTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Characteristics_Products1`
    FOREIGN KEY (`ProductID`)
    REFERENCES `WebShop`.`Products` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;